# Generated by Django 5.0.4 on 2024-05-03 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subchannel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.subchannel'),
        ),
    ]
