# Generated by Django 5.0.4 on 2024-05-03 03:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_message_subchannel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='channel_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
