# Generated by Django 5.0.4 on 2024-05-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_channels_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='subchannel',
            name='unique_key',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
