# Generated by Django 4.2.13 on 2024-05-16 11:24

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_account_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='channel_picture',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.get_default_profile_path),
        ),
    ]
