# Generated by Django 4.2.13 on 2024-05-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_channels_channel_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
